spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        package-to-scan: com.example.FakeApiProducts.infrastructure.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8484

api:
  security:
    token:
      secret: minha-key

kafka:
   consumer:
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     auto-offset-reset: earliest